-- MTM Stars Supabase setup / upgrade
-- Run this once in Supabase SQL Editor.
-- Safe to run again: existing tables/settings are preserved.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  price numeric not null default 0,
  tag text default '',
  category text default '',
  rate numeric default 5,
  n integer default 0,
  image_url text default '',
  description text default '',
  active boolean default true,
  featured boolean not null default true,
  sort_order integer default 0,
  created_at timestamptz default now()
);

alter table public.products add column if not exists featured boolean not null default true;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  description text default '',
  image_url text default '',
  sort_order integer default 0,
  active boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value text default ''
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text not null,
  message text not null,
  created_at timestamptz default now()
);

insert into public.site_settings(key,value) values
 ('phone',''),('whatsapp',''),('email',''),('address',''),
 ('about_title','More than a brand. A lifestyle.'),
 ('about_text','MTM Stars equips athletes, dreamers and champions with premium sports gear. From goalkeeper gloves and match footballs to boxing gloves, karate suits and performance hosiery, every piece is made to help you play, train and perform at your best.'),
 ('about_image_url',''),('about_pillars','Play | Train | Perform')
on conflict (key) do nothing;

insert into public.categories(name,slug,description,sort_order,active)
values
 ('Goalkeeper gloves','goalkeeper-gloves','Grip · Control · Confidence',1,true),
 ('Hosiery','hosiery','Comfort · Support · Performance',2,true),
 ('Football','football','Play · Train · Win',3,true),
 ('Boxing gloves','boxing-gloves','Power · Protection · Progress',4,true),
 ('Karate suit','karate-suit','Discipline · Focus · Strength',5,true)
on conflict (name) do nothing;

-- Storage bucket used for product, category and About Us images.
insert into storage.buckets (id,name,public) values ('product-images','product-images',true)
on conflict (id) do update set public=true;

alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.site_settings enable row level security;
alter table public.contact_messages enable row level security;

drop policy if exists "Public read active products" on public.products;
create policy "Public read active products" on public.products for select using (active = true);

drop policy if exists "Admins manage products" on public.products;
create policy "Admins manage products" on public.products for all to authenticated using (true) with check (true);

drop policy if exists "Public read active categories" on public.categories;
create policy "Public read active categories" on public.categories for select using (active = true);

drop policy if exists "Admins manage categories" on public.categories;
create policy "Admins manage categories" on public.categories for all to authenticated using (true) with check (true);

drop policy if exists "Public read settings" on public.site_settings;
create policy "Public read settings" on public.site_settings for select using (true);

drop policy if exists "Admins manage settings" on public.site_settings;
create policy "Admins manage settings" on public.site_settings for all to authenticated using (true) with check (true);

drop policy if exists "Anyone can send contact messages" on public.contact_messages;
create policy "Anyone can send contact messages" on public.contact_messages for insert to anon, authenticated with check (true);

drop policy if exists "Admins read contact messages" on public.contact_messages;
create policy "Admins read contact messages" on public.contact_messages for select to authenticated using (true);

drop policy if exists "Public read product images" on storage.objects;
create policy "Public read product images" on storage.objects for select using (bucket_id='product-images');

drop policy if exists "Admins upload product images" on storage.objects;
create policy "Admins upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images');

drop policy if exists "Admins update product images" on storage.objects;
create policy "Admins update product images" on storage.objects for update to authenticated using (bucket_id='product-images') with check (bucket_id='product-images');

drop policy if exists "Admins delete product images" on storage.objects;
create policy "Admins delete product images" on storage.objects for delete to authenticated using (bucket_id='product-images');

-- Keep all currently active products featured by default after upgrading an older database.
update public.products set featured=true where featured is null;


-- Rich media for About Us and product detail pages.
create table if not exists public.product_media (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  url text not null,
  media_type text not null default 'image',
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.about_media (
  id uuid primary key default gen_random_uuid(),
  url text not null,
  media_type text not null default 'image',
  sort_order integer default 0,
  created_at timestamptz default now()
);

alter table public.product_media enable row level security;
alter table public.about_media enable row level security;

drop policy if exists "Public read product media" on public.product_media;
create policy "Public read product media" on public.product_media for select using (true);
drop policy if exists "Admins manage product media" on public.product_media;
create policy "Admins manage product media" on public.product_media for all to authenticated using (true) with check (true);

drop policy if exists "Public read about media" on public.about_media;
create policy "Public read about media" on public.about_media for select using (true);
drop policy if exists "Admins manage about media" on public.about_media;
create policy "Admins manage about media" on public.about_media for all to authenticated using (true) with check (true);
